# Generated by Django 4.0.4 on 2022-05-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('localization', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('ip', models.GenericIPAddressField()),
                ('available_space', models.DecimalField(decimal_places=2, max_digits=10)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(default='R@nd0mP@ss', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('version', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compatible_model', models.CharField(max_length=25)),
                ('file', models.FileField(upload_to='scripts')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('success', models.BooleanField(default=False)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.router')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.script')),
            ],
        ),
    ]
