# Generated by Django 4.0.3 on 2022-04-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='password',
            field=models.CharField(default='R@nd0mP@ss', max_length=30),
        ),
    ]
