# Generated by Django 4.0.4 on 2022-06-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_deployment_id_alter_router_id_alter_script_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='logFile',
            field=models.FileField(default='', upload_to='output'),
        ),
    ]
