# Generated by Django 4.0.4 on 2022-06-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_deployment_logfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='porta',
            field=models.IntegerField(default=22),
        ),
    ]
