# Generated by Django 4.0.4 on 2022-06-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_router_porta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='available_space',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
